# Generated by Django 5.2.2 on 2025-06-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img_URL',
        ),
    ]
